### ISSUE TITLE
Region locked lyrics

### ISSUE THREAD

**Issue by SpookyO** [akashrchandran/spotify-lyrics-api#15]
So sometimes, the track id is correct and spotify has the lyrics but this api throw an error, like couldn't find the lyrics! But when i try with the api u guys are using works fine! So maybe try fixing the problem?

**Comment by akashrchandran** [comment]
Could you share the track id, would like to recreate the problem.

**Comment by SpookyO** [comment]
Here it is:
URL: https://open.spotify.com/track/23zmOYPltaN6KTgloPQGLX
Track ID: 23zmOYPltaN6KTgloPQGLX
Note: The language is NOT English and Both URL and Track ID returns the error! (Sorry for late reply)

**Comment by akashrchandran** [comment]
> I tried recreating the issue but there is no error in the code base. Spotify does actually respond that there is no lyrics for the track, so I tried playing the song on Spotify app and there was no lyrics option. Even I tried playing it in two different accounts and still no lyrics option.

![image](https://user-images.githubusercontent.com/78685510/216370299-92232ebd-f3eb-41ba-9e95-a9c67306b20b.png)

> Both the account used where Indian based accounts, so just to check if lyrics is region locked or not, I tried with a Germany account. To my surprise the lyrics option was available.

![image](https://user-images.githubusercontent.com/78685510/216370862-a60f383a-d552-4d68-96e2-3b1c69082ffc.png)

> As the API also uses Indian account, it wasn't able to get the lyrics.

*It will be better if you self-host the API with an account based on any other country to get the lyrics.*

__I have no idea why Spotify region locks lyrics. If I find any way to bypass it I will update.__

**Comment by SpookyO** [comment]
> > I tried recreating the issue but there is no error in the code base. Spotify does actually respond that there is no lyrics for the track, so I tried playing the song on Spotify app and there was no lyrics option. Even I tried playing it in two different accounts and still no lyrics option.
> 
> ![image](https://user-images.githubusercontent.com/78685510/216370299-92232ebd-f3eb-41ba-9e95-a9c67306b20b.png)
> 
> > Both the account used where Indian based accounts, so just to check if lyrics is region locked or not, I tried with a Germany account. To my surprise the lyrics option was available.
> 
> ![image](https://user-images.githubusercontent.com/78685510/216370862-a60f383a-d552-4d68-96e2-3b1c69082ffc.png)
> 
> > As the API also uses Indian account, it wasn't able to get the lyrics.
> 
> _It will be better if you self-host the API with an account based on any other country to get the lyrics._
> 
> **I have no idea why Spotify region locks lyrics. If I find any way to bypass it I will update.**

Ohk, Thanks for the update!

**Comment by ego-lay-atman-bay** [comment]
> I have no idea why Spotify region locks lyrics. If I find any way to bypass it I will update.

Pretty sure it's just a licensing issue. There are some songs that I've put lyrics onto musixmatch, but they only show up on yt music and spotify outside the US. I talked to some musixmatch people about it, and they said it was just licensing.
