### ISSUE TITLE
Can't get lyrics for this track https://open.spotify.com/track/7lb9nshCN6cz4gYCjiRg6J

### ISSUE THREAD

**Issue by maxrave-dev** [akashrchandran/spotify-lyrics-api#18]
On Spotify, this track's lyrics are still available:
![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/113747128/8f9f4f24-f4b2-4c7a-8d85-eca160216635)

But API return the error:
![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/113747128/834f3a09-9068-4d53-8f8a-977e7deaafdb)

Please fix it! Thanks

**Comment by akashrchandran** [comment]
This seems same as of #15, detailed answer is the https://github.com/akashrchandran/spotify-lyrics-api/issues/15#issuecomment-1413955222.
