### ISSUE TITLE
Api Giudlines

### ISSUE THREAD

**Issue by Drag-3** [akashrchandran/spotify-lyrics-api#19]
I want to use your API for a project. I just want to know, how many requests can I make at once, and how fast I can make requests. I do not want to accidentally DOS your server while testing my project.

**Comment by akashrchandran** [comment]
@Drag-3 thank you for asking. As you may have noticed it is hosted on Heroku and I am on the Eco tier (just google it). There is no rate limiting or anything from my side but there are some [limitations on Heroku](https://devcenter.heroku.com/articles/limits) . 

And Eco tier only comes with 512 MB of RAM which is more than enough for this app, but higher traffic may cause it to crash. A better way would be hosting this API yourself and scale depending on your usage needs. It's fairly easy to deploy and if you need help make sure to let me know. 

I see most of your projects are in python, you may have a look at [Syrics](https://github.com/akashrchandran/syrics). I have [modular](https://github.com/akashrchandran/syrics#use-as-a-module) option so you can make requests using it and get raw lyrics.

**Comment by Drag-3** [comment]
@akashrchandran Thank you for the quick response. The Syrics module does fulfill all of my needs as of now so I'll be being that.
