### ISSUE TITLE
CORS Error when fetching

### ISSUE THREAD

**Issue by LemonProg** [akashrchandran/spotify-lyrics-api#21]
Hey, I am using this api in a Node.js website, but when I try to fetch any song, i got this error : 
`Access to fetch at 'https://spotify-lyric-api.herokuapp.com/?trackid=1GelyurdH5LBWReoScJF59' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.`
To fix that I tried to use some cors proxy, but there are not stable, so can you please fix the API to allow every origins ? Or if you want, here my production url "https://lemon-typer.onrender.com/", so you can only allow trusted website. Thank you

**Comment by akashrchandran** [comment]
I believe I've resolved the problem. Could you kindly verify it and let me know your feedback?

**Comment by LemonProg** [comment]
I fixed my issue using cors anywhere, but I can tell you if it's working tonight 👍🏻
