### ISSUE TITLE
Default Heroku Instance often returning "No lyrics for this track" error

### ISSUE THREAD

**Issue by aviwad** [akashrchandran/spotify-lyrics-api#25]
Examples: Try the link in the README. Have to refresh 3/4 times to get lyrics. This has suddenly started today. Noticed in my application. Would you suggest I self-host with my own sp_dc key? Is my app perhaps spamming your heroku instance too much? I cache every download

**Comment by akashrchandran** [comment]
Consider hosting the app on your server. It's getting a lot of spam. While I'm not certain if it's connected, the app performed flawlessly on my local setup. To be cautious, I've temporarily switched it to maintenance mode to prevent spam. I'll re-enable it soon. In the meantime, I'll check the code for any issues.

**Comment by akashrchandran** [comment]
Can you please check now? It appears to be working well.
