### ISSUE TITLE
Alternative API 

### ISSUE THREAD

**Issue by Joeeeeb5** [akashrchandran/spotify-lyrics-api#27]
Spotify doesn't provide lyrics for free tier accounts anymore. Make it possible for people to use an alternative API, like musixmatch or genius to find lyrics.

**Comment by Paxsenix0** [comment]
Hello, i'm still beginner and i found MusixMatch API to get lyrics, and i'm trying to making it on PHP
You can see my repo https://github.com/Paxsenix0/MusixMatch-Lyrics/
I'm sorry if the code looks weird:(

**Comment by Joeeeeb5** [comment]
I think it looks good so far, good luck! :)

**Comment by akashrchandran** [comment]
Please check the issue #29

**Comment by akashrchandran** [comment]
Please check the issue #29
