### ISSUE TITLE
Minor Repository Updates

### ISSUE THREAD

**Issue by akashrchandran** [akashrchandran/spotify-lyrics-api#29]
# Heroku-hosted API Updates

We've made some updates to the Heroku-hosted API. The main issue we encountered was a high volume of incoming spam requests, which made it difficult for others to use. To address this, we've changed the API link. If spamming continues, we may need to implement rate limiting. You can find the update details below.

- The API URL has been updated to `https://spotify-lyric-api-984e7b4face0.herokuapp.com/`.
- The account used has been upgraded to a Premium [Indian] account, ensuring that all available lyrics in this region are accessible.
- Sustaining free services may become challenging. If you wish to support us, please consider making a donation for the upkeep of the Heroku and Spotify accounts.
- While the Premium account and Heroku deployment may not be perpetual, the code is available for self-hosting and can be utilized with your own premium account.

## Donation links:
- Github Sponsor: https://github.com/sponsors/akashrchandran/
- Kofi: https://ko-fi.com/akashrchandran
- PayPal: https://www.paypal.me/akashrchandran

**Comment by yagdev** [comment]
Thanks a lot for ensuring that this API is kept online despite all difficulties. To ensure the API is not overloaded I highly advise developers to implement lyric caching to avoid performing the same request over and over without necessity and only using this API as a fallback for when the Spotify API can't return the lyrics (although this one is more overkill and might defeat the purpose of using the API in some ways).
Again, thank you for maintaining this service and thank you for the Premium upgrade as I've noticed lots more song lyrics are available now.
