### ISSUE TITLE
Add as a lyrics source for LyricsX

### ISSUE THREAD

**Issue by rounakdatta** [akashrchandran/spotify-lyrics-api#30]
[LyricsX](https://github.com/ddddxxx/LyricsX) used to be an amazing service, but nowadays it hasn't been behaving consistently due to the lyrics sources not working reliably. Could your API endpoint be possibly added as a source here?

**Comment by akashrchandran** [comment]
You can use it, but I'm not sure how long I can keep the API running. It's better if you host it on your own and then add it to the other program.
