### ISSUE TITLE
Always return "lyrics for this track is not available on spotify!"

### ISSUE THREAD

**Issue by Mann202** [akashrchandran/spotify-lyrics-api#31]
![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/95089843/e7c1a2d8-ec27-4d78-b136-c5a77014a08f)
I'm cloning your repo and run it locally but it seem encountered problem, can you help me solve this problem

my cache file
![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/95089843/896ccacd-2278-4e60-adfe-f73752635725)

**Comment by akashrchandran** [comment]
Is the track ID you provided correct? It doesn't seem to work when I try it. Also, do you have a premium account?

**Comment by Mann202** [comment]
yes, i have premium account and using it in spotify web playback sdk as well

i tried to get lyric from track that i can get lyric from your api but it return the same
![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/95089843/8ae98cb5-69c0-4a28-88de-636cafa3a39c)

**Comment by Mann202** [comment]
As metioned in email, i find that your api only facing problem to get random lyric from some tracks of Taylor Swift, Charlie Puth,... but another artist's track can get lyrics. Do you think it because blocked region?

**Comment by akashrchandran** [comment]
Are there any error messages showing up on the terminal where you're running the application?

**Comment by Mann202** [comment]
in further research based on your app, now i can fetch lyrics without your api

axios.get(`https://spclient.wg.spotify.com/color-lyrics/v2/track/${trackID}/image/https%3A%2F%2Fi.scdn.co%2Fimage%2Fab67616d0000b27325e6b25d49687cd63f7a034e?format=json&vocalRemoval=false&market=from_token`, {
                headers: {
                    "App-platform": "WebPlayer",
                    "Authorization": `Bearer ${access_token}`,
                    "Client-Token": "Client-token here"
                }
            })
