### ISSUE TITLE
Always lyrics not found message

### ISSUE THREAD

**Issue by SpookyO** [akashrchandran/spotify-lyrics-api#32]
Hey, so i have been reusing this api again, and seems like *most* of the lyrics of track id/url gives error, example: Faded, Alone, believer etc, 
I also tried to use the base api underlying in this api but when i use get_access_token spotify api endpoint to get token (without sp dc) and then make a get request through the base api with
headers={
'App-platform': 'WebPlayer',
'authorization': 'Bearer access_token'
}
Always seems to return 400 Bad request and if i use this endpoint 

> https://accounts.spotify.com/api/token and make a post request and try the access token given by this api, then the lyrics api seems to return 403 with a text 'rbac: access denied'

**Comment by akashrchandran** [comment]
Apologies for the delayed response; I've been quite occupied with real-life matters. Did you manage to resolve the issue?

**Comment by SpookyO** [comment]
Yes i have resolved the issue, turns you this v2 endpoint now always
requires cookie :/ so yeah the current api of yours is always giving error
so had to make my own. Thanks!

**Comment by akashrchandran** [comment]
Good to know, ☺️.
