### ISSUE TITLE
returned null from using the package example

### ISSUE THREAD

**Issue by vosqi** [akashrchandran/spotify-lyrics-api#40]
```php
<?php
require('./vendor/autoload.php');

$spotify = new SpotifyLyricsApi\Spotify(""); 
$spotify->checkTokenExpire();
$reponse = $spotify -> getLyrics(track_id: "1418IuVKQPTYqt7QNJ9RXN");

$json = $reponse;
$data = json_decode($json, true);
$pretty_json = json_encode($data, JSON_PRETTY_PRINT);

echo $pretty_json
?>
```
![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/74667208/786bd66c-8c3d-4585-adca-d2548e7f17d6)
![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/74667208/cfd47334-007e-4c95-b02f-c55fb7feb847)

**Comment by akashrchandran** [comment]
Make sure you're using a premium account. Spotify has made lyrics a premium feature.
