### ISSUE TITLE
Unsynced Lyrics Bug

### ISSUE THREAD

**Issue by bitit0** [akashrchandran/spotify-lyrics-api#41]
The API used to work perfectly fine, now it only shows unsynced lyrics and only 5 at a time. 

Example: `{"error":false,"syncType":"UNSYNCED","lines":[{"startTimeMs":"0","words":"Baby, baby","syllables":[],"endTimeMs":"0"},{"startTimeMs":"0","words":"There will always be a space for you and me","syllables":[],"endTimeMs":"0"},{"startTimeMs":"0","words":"Right where you left it","syllables":[],"endTimeMs":"0"},{"startTimeMs":"0","words":"And just maybe","syllables":[],"endTimeMs":"0"},{"startTimeMs":"0","words":"Enough time will pass","syllables":[],"endTimeMs":"0"}]}`

Probably related, the web browser version of the spotify player shows the lyrics not synced as well. It seems to work fine in the app though.

![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/3123487/d149f91c-8df8-4563-a044-232e205995db)

**Comment by akashrchandran** [comment]
It seems that Spotify has finally made lyrics a premium feature.  Even in the Spotify app, I am getting the same thing. I have the latest version, haven't check old build it may be still working.

![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/78685510/280272c3-6959-48ac-8899-5a8f96b3d668)
