### ISSUE TITLE
Internal Error: Failure to open Required file

### ISSUE THREAD

**Issue by Rcuz8** [akashrchandran/spotify-lyrics-api#42]
## Description
I followed the setup steps:
``` 
$ git clone https://github.com/akashrchandran/spotify-lyrics-api.git
$ cd spotify-lyrics-api
$ php -S localhost:8000 api/index.php
```

And, when pinging an endpoint, The server threw a `Failure to open Required file` error on this line:
```php
require_once __DIR__ . '/../vendor/autoload.php';
```

## Potential fix
The issue resolved when I changed the line above to:
```
require_once __DIR__ . '/../src/Spotify.php';
require_once __DIR__ . '/../src/SpotifyException.php';
```

**Comment by akashrchandran** [comment]
This is for when you're using the API as a package to obtain lyrics. Rather than downloading the repository, you should use Composer to install it.

```bash
composer require akashrchandran/spotify-lyrics-api
```
