### ISSUE TITLE
Heroku app dead

### ISSUE THREAD

**Issue by TomasHubelbauer** [akashrchandran/spotify-lyrics-api#43]
Hi, I am trying to check out the demo link at https://spotify-lyric-api.herokuapp.com/?trackid=5f8eCNwTlr0RJopE9vQ6mB but Heroku returns a "nothing is here" error.

![image](https://github.com/akashrchandran/spotify-lyrics-api/assets/6831144/891dae64-1e26-4e55-8948-a6633304b58e)

At the same time, I see in #41 that lyrics is now a premium Spotify feature, so I am wondering if the app can no longer use that Spotify API even if it was still up?

**Comment by TomasHubelbauer** [comment]
I've not tried running this repository locally, but I have reversed the unofficial lyrics API just now to see if it still works and it does, but I don't have a non-Premium token to test it with. It works with my Premium token and here is a JavaScript snippet in case it is useful to anyone:

```typescript
const response = await fetch(
  `https://spclient.wg.spotify.com/color-lyrics/v2/track/${id}?format=json`,
  {
    headers: { authorization, 'app-platform': 'WebPlayer' }
  }
);
if (response.ok) {
  const data = await response.json();
  // ...data.lyrics
}
else {
  // Unauthorized, Not Found etc.
}
```

**Comment by akashrchandran** [comment]
You can deploy your own version on the Vercel platform for free using your own account. Heroku has transitioned to a paid model and eliminated the free tier, so I had to stop using it to avoid incurring charges.
