### ISSUE TITLE
CORS-Policy Problem

### ISSUE THREAD

**Issue by Benji4564** [akashrchandran/spotify-lyrics-api#7]
access to fetch at 'https://spotify-lyric-api.herokuapp.com/?url=%20undefined?autoplay=true' from origin 'https://www.be-ready.software' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

**Comment by akashrchandran** [comment]
I have updated the code, could you check and reply.

**Comment by Benji4564** [comment]
Yes it now works, thanks
